### ISSUE TITLE
Why is interceptors api not async ? 

### ISSUE THREAD

**Issue by DanielCardonaRojas** [cfug/dio#1334]
- [x] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

I was reading throught the documentation and it seemed a bit odd to me that interceptor related methods `onError onRequest onResponse` all return `void` instead of `Future<void>` or `FutureOr<void>`

This implies hacky was to get around and linter errors.

**Comment by wendux** [comment]
Using `handler.xx`  instead of returning future in interceptors.

Before 4.0, the interceptor returned `Future`, but a problem with `Future` is that there are only two states: success and failure. But in interceptors, developers may expect to do more. For example, when the **request** interceptor resolves directly, the developer can specify to continue to execute the subsequent **response** interceptor or or skip the subsequent **response** interceptor. At this time, just return  Future can't work . Therefore, after 4.0, the interceptor introduced a `handler` object. We can clearly tell the dio what to do next through the `handler` in the interceptor. Usually, we call `handler.next` directly to execute the next interceptor.

**Comment by DanielCardonaRojas** [comment]
But still handle does not allow handing in a future, so you would have to use await  in onResponse body and get linter warnings because method is not async to be able to provide a value into the handler.

Is there another mechanism for chaining requests for example ?

**Comment by kuhnroyal** [comment]
From my experience, it is completely fine to make your interceptor functions `async`, `await` something and then call `handler.next`.

If you want to avoid lint warnings, you can also change the return type to `Future<void>` in overridden functions, that is perfectly fine.
